title: Leave Your Thoughts Behind!
author: Inca Gt
email: your-email@domain.com
description: > # this means to ignore newlines until "baseurl:"
  What have you! Just leave your thoughts behind!

# social links
twitter_username: your-twitter-handle # DO NOT include the @ character, or else the build will fail!
github_username:  shivmos # DO NOT include the @ character, or else the build will fail!

show_excerpts: true # set to false to remove excerpts on the homepage
theme: minima
